"""Add password reset and verification fields

Revision ID: 86ee08a3d9b5
Revises: f25c4f0a888f
Create Date: 2026-08-06 00:13:03.302835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ee08a3d9b5'
down_revision: Union[str, Sequence[str], None] = 'f25c4f0a888f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verification_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_email_verification_hash'), 'users', ['email_verification_hash'], unique=True)
    op.create_index(op.f('ix_users_password_reset_hash'), 'users', ['password_reset_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_reset_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_hash'), table_name='users')
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'email_verification_hash')
    op.drop_column('users', 'password_reset_expires_at')
    op.drop_column('users', 'password_reset_hash')
    # ### end Alembic commands ###
